# -----------------------------
# NOTE: https://github.com/marketplace/actions/github-tag-bump
# example 2: on merge to master/main
# -----------------------------

name: 'Bump version [TEST]'
env:
  PATCH_WORDING: 'PATCH,patch,fix,hotfix,add'
  MINOR_WORDING: 'MINOR,minor,feat'
  MAJOR_WORDING: 'MAJOR,,major,BREAKING'
'on':
  pull_request:
    types:
      - closed
    branches:
      - dev
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Datatypes Testing
        run: echo "True"
      - name: Checkout source code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/setup-node@v3
        with:
          node-version: 16 
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"
      - name: PATCH - check
        if: '${{ contains(env.PATCH_WORDING, github.event.pull_request.title) }}'
        run: |
          echo "Patch Bump Detected"
          npm version patch
      - name: MINOR - check
        if: '${{ contains(env.MINOR_WORDING, github.event.pull_request.title) }}'
        run: |
          echo "Minor Bump Detected"
          npm version minor
      - name: MAJOR - check
        if: '${{ contains(env.MAJOR_WORDING, github.event.pull_request.title) }}'
        run: |
          echo "Major Bump Detected"
          npm version major
      - name: Git push version bump
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: git push origin dev --follow-tags --force
      - id: set-version
        name: Output version change
        run: npm pkg get version
