# -----------------------------
# NOTE: https://github.com/marketplace/actions/github-tag-bump
# example 2: on merge to master/main
# -----------------------------

name: Bump version [TEST]

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:

    # NOTE: CUSTOM IMPLEMENTATION
    - name: 'Checkout source code'
      uses: 'actions/checkout@v3'
    - name: Dump GitHub context
      run: |
        echo "complete Github Context ${{ toJson(github) }}"
        echo "The title of PR is: ${{ github.event.pull_request.title }}"
    
    # - name: Apply version bump (major)
    #   if: contains(github.event.pull_request.labels.*.name, 'major')
    #   run: npm version major
    # - name: Apply version bump (minor)
    #   if: contains(github.event.pull_request.labels.*.name, 'minor')
    #   run: npm version minor
    # - name: Apply version bump (patch)
    #   if: contains(github.event.pull_request.labels.*.name, 'patch')
    #   run: npm version patch